import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
// import { ThemeProvider } from "@/components/ThemeProvider"; // Remove this line
import { Toaster } from "sonner";

export const metadata = {
  title: "BitCoin Live",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased h-full bg-gray-50 text-gray-900 transition-colors duration-300`}
      >
        {/* <ThemeProvider> */}
          {children}
          <Toaster richColors theme="system" position="top-right" />
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}